[tool.poetry]
name = "Nukes-admin-bot"
version = "0.0.1"
description = "Simple bot that helps me administrate my chats."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/admin-bot"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "6.10"
alembic = "1.0"

telethon = "^1.10"

SQLAlchemy = "^1.2"
sqlalchemy-utils = "^0.33"
psycopg2-binary = "^2.8"

toml = "^0.10"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
